# Generated by Django 5.2.4 on 2025-08-08 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20250807_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(choices=[('verification', 'Verification'), ('welcome', 'Welcome'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('other', 'Other')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('error', 'Error')], default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Email',
                'verbose_name_plural': 'Registros de Email',
                'ordering': ['-created_at'],
            },
        ),
    ]
